// <auto-generated />
using AnimalShelter.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AnimalShelter.Migrations
{
    [DbContext(typeof(AnimalShelterContext))]
    [Migration("20211029230352_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("AnimalShelter.Models.Animal", b =>
                {
                    b.Property<int>("AnimalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Breed")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Description")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Gender")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Species")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("Weight")
                        .HasColumnType("int");

                    b.HasKey("AnimalId");

                    b.ToTable("Animals");

                    b.HasData(
                        new
                        {
                            AnimalId = 1,
                            Age = 1,
                            Breed = "Texas-Heeler",
                            Description = "Arlo is a fun loving pup with a lot of energy.",
                            Gender = "male",
                            Name = "Arlo",
                            Species = "dog",
                            Weight = 39
                        },
                        new
                        {
                            AnimalId = 2,
                            Age = 3,
                            Breed = "Lab",
                            Description = "Ollie is a fun loving pup with a lot of energy.",
                            Gender = "female",
                            Name = "Ollie",
                            Species = "dog",
                            Weight = 42
                        },
                        new
                        {
                            AnimalId = 3,
                            Age = 6,
                            Breed = "Pit-Bull",
                            Description = "Indigo is a fun loving pup with a lot of energy.",
                            Gender = "male",
                            Name = "Indigo",
                            Species = "dog",
                            Weight = 35
                        },
                        new
                        {
                            AnimalId = 4,
                            Age = 9,
                            Breed = "Corgi",
                            Description = "Kermit is a fun loving pup with a lot of energy.",
                            Gender = "female",
                            Name = "Kermit",
                            Species = "dog",
                            Weight = 24
                        },
                        new
                        {
                            AnimalId = 5,
                            Age = 2,
                            Breed = "Austrailian-Sheppard",
                            Description = "Danzig is a fun loving pup with a lot of energy.",
                            Gender = "male",
                            Name = "Danzig",
                            Species = "dog",
                            Weight = 26
                        },
                        new
                        {
                            AnimalId = 6,
                            Age = 6,
                            Breed = "Main coon",
                            Description = "Sam is an easy going boy. He loves to lounge around with people and chase lasers.",
                            Gender = "male",
                            Name = "Sam",
                            Species = "cat",
                            Weight = 15
                        },
                        new
                        {
                            AnimalId = 7,
                            Age = 4,
                            Breed = "Bengal",
                            Description = "Fred is an easy going boy. He loves to lounge around with people and chase lasers.",
                            Gender = "male",
                            Name = "Fred",
                            Species = "cat",
                            Weight = 13
                        },
                        new
                        {
                            AnimalId = 8,
                            Age = 2,
                            Breed = "Siberian",
                            Description = "Lillie is an easy going gale. She loves to lounge around with people and chase lasers.",
                            Gender = "female",
                            Name = "Lillie",
                            Species = "cat",
                            Weight = 10
                        },
                        new
                        {
                            AnimalId = 9,
                            Age = 9,
                            Breed = "Ragdoll",
                            Description = "Barb is an easy going gale. She loves to lounge around with people and chase lasers.",
                            Gender = "female",
                            Name = "Barb",
                            Species = "cat",
                            Weight = 9
                        },
                        new
                        {
                            AnimalId = 10,
                            Age = 12,
                            Breed = "Siamese",
                            Description = "Rust is an easy going boy. He loves to lounge around with people and chase lasers.",
                            Gender = "male",
                            Name = "Rust",
                            Species = "cat",
                            Weight = 15
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
